sonar.projectKey=app_puyango
sonar.projectName=app_puyango
sonar.projectVersion=1.0
sonar.login=sqp_1bee4bb7cad0ab86245906c7908372d0b54c54b1

sonar.sources=src

sonar.exclusions=**/node_modules/**, **/dist/**, **/build/**

sonar.javascript.lcov.reportPaths=coverage/lcov-report/index-lcov-report.json
sonar.javascript.node.js.executablePath=node

sonar.language=js
sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
